"""Add guest_id to Order model

Revision ID: 0998aaef8a7b
Revises: 3304f6616f3b
Create Date: 2026-01-16 14:22:18.969900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0998aaef8a7b'
down_revision = '3304f6616f3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('guest_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_guest_id'), 'orders', ['guest_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_guest_id'), table_name='orders')
    op.drop_column('orders', 'guest_id')
    # ### end Alembic commands ###
