"""Resync after main branch pull (final attempt)

Revision ID: 0e00b46f0f63
Revises: 
Create Date: 2025-12-22 19:54:12.033033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e00b46f0f63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('photos', sa.Column('object_name', sa.Text(), nullable=False, server_default='placeholder'))
    op.drop_column('photos', 'watermark_url')
    op.drop_column('photos', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('url', sa.TEXT(), server_default=sa.text("'placeholder'::text"), autoincrement=False, nullable=False))
    op.add_column('photos', sa.Column('watermark_url', sa.TEXT(), server_default=sa.text("'placeholder'::text"), autoincrement=False, nullable=False))
    op.drop_column('photos', 'object_name')
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###
