"""Add customer_email to Order model

Revision ID: 1208a85e9ab6
Revises: 5d33e0b7bd11
Create Date: 2025-12-26 21:06:49.109768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1208a85e9ab6'
down_revision = '5d33e0b7bd11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'customer_email')
    # ### end Alembic commands ###
