"""Add many-to-many relationship between albums and combos

Revision ID: 2640c647eaf0
Revises: 30843619c624
Create Date: 2026-01-13 23:56:50.343918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2640c647eaf0'
down_revision = '30843619c624'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
