"""Add default_photo_price to Album

Revision ID: 30843619c624
Revises: dcec7f2ac121
Create Date: 2026-01-12 19:40:28.327187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30843619c624'
down_revision = 'dcec7f2ac121'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('default_photo_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'default_photo_price')
    # ### end Alembic commands ###
