"""Add user_email and discount_code to Cart

Revision ID: 3304f6616f3b
Revises: 72ed40b3c933
Create Date: 2026-01-15 20:53:02.570014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3304f6616f3b'
down_revision = '72ed40b3c933'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('user_email', sa.String(), nullable=True))
    op.add_column('carts', sa.Column('discount_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'discount_code')
    op.drop_column('carts', 'user_email')
    # ### end Alembic commands ###
