"""Actualizar relaciones de fotografo y ganancias

Revision ID: 3ad2ffc8a500
Revises: f4cc8eadd474
Create Date: 2026-02-04 16:48:04.235580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad2ffc8a500'
down_revision = 'f4cc8eadd474'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Actualizar la clave foránea en la tabla 'earnings'
    op.drop_constraint('earnings_photographer_id_fkey', 'earnings', type_='foreignkey')
    op.create_foreign_key(
        'earnings_photographer_id_fkey',
        'earnings', 'photographers',
        ['photographer_id'], ['id'],
        ondelete='RESTRICT'
    )

    # Actualizar la clave foránea en la tabla 'photo_sessions'
    op.drop_constraint('photo_sessions_photographer_id_fkey', 'photo_sessions', type_='foreignkey')
    op.create_foreign_key(
        'photo_sessions_photographer_id_fkey',
        'photo_sessions', 'photographers',
        ['photographer_id'], ['id'],
        ondelete='RESTRICT'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revertir la clave foránea en la tabla 'photo_sessions'
    op.drop_constraint('photo_sessions_photographer_id_fkey', 'photo_sessions', type_='foreignkey')
    op.create_foreign_key(
        'photo_sessions_photographer_id_fkey',
        'photo_sessions', 'photographers',
        ['photographer_id'], ['id']
    )

    # Revertir la clave foránea en la tabla 'earnings'
    op.drop_constraint('earnings_photographer_id_fkey', 'earnings', type_='foreignkey')
    op.create_foreign_key(
        'earnings_photographer_id_fkey',
        'earnings', 'photographers',
        ['photographer_id'], ['id']
    )
    # ### end Alembic commands ###
