"""Add public_id to Order model

Revision ID: 5d33e0b7bd11
Revises: 0e00b46f0f63
Create Date: 2025-12-26 20:50:09.747081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d33e0b7bd11'
down_revision = '0e00b46f0f63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('public_id', sa.UUID(), nullable=True))
    op.execute('UPDATE orders SET public_id = gen_random_uuid()')
    op.alter_column('orders', 'public_id', nullable=False)
    op.drop_index(op.f('ix_orders_uuid'), table_name='orders')
    op.create_index(op.f('ix_orders_public_id'), 'orders', ['public_id'], unique=True)
    op.drop_column('orders', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_orders_public_id'), table_name='orders')
    op.create_index(op.f('ix_orders_uuid'), 'orders', ['uuid'], unique=True)
    op.drop_column('orders', 'public_id')
    # ### end Alembic commands ###
