"""Add short_id to SavedCart

Revision ID: 72ed40b3c933
Revises: 2640c647eaf0
Create Date: 2026-01-15 19:39:51.521338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ed40b3c933'
down_revision = '2640c647eaf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_carts', sa.Column('short_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_saved_carts_short_id'), 'saved_carts', ['short_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_carts_short_id'), table_name='saved_carts')
    op.drop_column('saved_carts', 'short_id')
    # ### end Alembic commands ###
