"""add guest_id to cart

Revision ID: 86e79dade900
Revises: 1208a85e9ab6
Create Date: 2026-01-05 19:40:36.277829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e79dade900'
down_revision = '1208a85e9ab6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('guest_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_carts_guest_id'), 'carts', ['guest_id'], unique=True)
    op.create_unique_constraint(None, 'carts', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='unique')
    op.drop_index(op.f('ix_carts_guest_id'), table_name='carts')
    op.drop_column('carts', 'guest_id')
    # ### end Alembic commands ###
