"""Add public_id and cart_state to saved_carts

Revision ID: a372208da709
Revises: 0998aaef8a7b
Create Date: 2026-01-23 19:47:10.351809

"""
from alembic import op
import sqlalchemy as sa
import random
import string

# revision identifiers, used by Alembic.
revision = 'a372208da709'
down_revision = '0998aaef8a7b'
branch_labels = None
depends_on = None

def _generate_short_id(length=6):
    characters = string.ascii_uppercase + string.digits
    return "".join(random.choice(characters) for _ in range(length))

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_carts', sa.Column('public_id', sa.String(), nullable=True))
    op.add_column('saved_carts', sa.Column('cart_state', sa.JSON(), nullable=True))

    # Populate existing rows with default values
    connection = op.get_bind()
    saved_carts_table = sa.Table('saved_carts', sa.MetaData(), sa.Column('id', sa.Integer, primary_key=True), sa.Column('public_id', sa.String), sa.Column('cart_state', sa.JSON))
    
    results = connection.execute(sa.select(saved_carts_table.c.id)).fetchall()
    for row in results:
        public_id = _generate_short_id()
        connection.execute(
            saved_carts_table.update().where(saved_carts_table.c.id == row.id).values(public_id=public_id, cart_state={})
        )

    # Now, alter the columns to be non-nullable
    op.alter_column('saved_carts', 'public_id', nullable=False)
    op.alter_column('saved_carts', 'cart_state', nullable=False)

    op.create_index(op.f('ix_saved_carts_public_id'), 'saved_carts', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_carts_public_id'), table_name='saved_carts')
    op.drop_column('saved_carts', 'cart_state')
    op.drop_column('saved_carts', 'public_id')
    # ### end Alembic commands ###
