"""add format to order item

Revision ID: dcec7f2ac121
Revises: 86e79dade900
Create Date: 2026-01-09 19:30:02.063355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcec7f2ac121'
down_revision = '86e79dade900'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('format', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'format')
    # ### end Alembic commands ###
