"""Add content_hash to Photo model

Revision ID: f4cc8eadd474
Revises: a372208da709
Create Date: 2026-02-03 23:43:49.159222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4cc8eadd474'
down_revision = 'a372208da709'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_files_id'), table_name='upload_files')
    op.drop_table('upload_files')
    op.drop_index(op.f('ix_upload_sessions_id'), table_name='upload_sessions')
    op.drop_table('upload_sessions')
    op.add_column('photos', sa.Column('content_hash', sa.String(length=256), nullable=True))
    op.drop_constraint('photos_object_name_key', 'photos', type_='unique')
    op.drop_constraint('photos_thumbnail_object_name_key', 'photos', type_='unique')
    op.create_index(op.f('ix_photos_content_hash'), 'photos', ['content_hash'], unique=False)
    op.drop_column('photos', 'thumbnail_object_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('thumbnail_object_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_photos_content_hash'), table_name='photos')
    op.create_unique_constraint(op.f('photos_thumbnail_object_name_key'), 'photos', ['thumbnail_object_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('photos_object_name_key'), 'photos', ['object_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('photos', 'content_hash')
    op.create_table('upload_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('upload_session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filesize', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'UPLOADED', 'FAILED', name='uploadfilestatus'), autoincrement=False, nullable=False),
    sa.Column('object_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kind', postgresql.ENUM('ORIGINAL', 'THUMBNAIL', name='uploadfilekind'), server_default=sa.text("'ORIGINAL'::uploadfilekind"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['upload_session_id'], ['upload_sessions.id'], name=op.f('upload_files_upload_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('upload_files_pkey')),
    sa.UniqueConstraint('object_name', name=op.f('upload_files_object_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_upload_files_id'), 'upload_files', ['id'], unique=False)
    op.create_table('upload_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('album_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'UPLOADING', 'COMPLETED', 'FAILED', 'CANCELLED', name='uploadsessionstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('upload_sessions_album_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('upload_sessions_pkey'))
    )
    op.create_index(op.f('ix_upload_sessions_id'), 'upload_sessions', ['id'], unique=False)
    # ### end Alembic commands ###
